# Generated by Django 5.1.6 on 2025-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='setdone',
            name='routine',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='day',
            field=models.CharField(default='MONDAY', max_length=10),
        ),
    ]
